import { ContactSimpleProps } from "./index";

export const defaultContent: ContactSimpleProps = {
  headline: "Get in touch",
  subheadline: "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
  fields: [
    {
      name: "name",
      label: "Name",
      type: "text",
      placeholder: "Your name",
      required: true,
    },
    {
      name: "email",
      label: "Email",
      type: "email",
      placeholder: "your@email.com",
      required: true,
    },
    {
      name: "phone",
      label: "Phone",
      type: "tel",
      placeholder: "+1 (555) 123-4567",
      required: false,
    },
    {
      name: "subject",
      label: "Subject",
      type: "select",
      placeholder: "Select a subject",
      required: true,
      options: [
        { value: "general", label: "General inquiry" },
        { value: "support", label: "Technical support" },
        { value: "sales", label: "Sales question" },
        { value: "partnership", label: "Partnership opportunity" },
        { value: "other", label: "Other" },
      ],
    },
    {
      name: "message",
      label: "Message",
      type: "textarea",
      placeholder: "How can we help you?",
      rows: 4,
      required: true,
    },
  ],
  submitText: "Send message",
  successMessage: "Thank you for your message. We'll get back to you within 24 hours.",
  contactInfo: {
    email: "hello@example.com",
    phone: "+1 (555) 123-4567",
    address: "123 Business Ave, Suite 100, San Francisco, CA 94105",
    hours: "Monday - Friday, 9am - 6pm PST",
  },
};

export const contentVariations: ContactSimpleProps[] = [
  // Minimal contact form
  {
    headline: "Contact us",
    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
      },
      {
        name: "message",
        label: "Message",
        type: "textarea",
        rows: 6,
        required: true,
      },
    ],
    submitText: "Send",
  },
  // Support form
  {
    headline: "Need help?",
    subheadline: "Our support team is here to assist you",
    fields: [
      {
        name: "name",
        label: "Full name",
        type: "text",
        placeholder: "John Doe",
        required: true,
      },
      {
        name: "email",
        label: "Email address",
        type: "email",
        placeholder: "john@example.com",
        required: true,
      },
      {
        name: "issue_type",
        label: "Issue type",
        type: "select",
        required: true,
        options: [
          { value: "bug", label: "Bug report" },
          { value: "feature", label: "Feature request" },
          { value: "account", label: "Account issue" },
          { value: "billing", label: "Billing question" },
          { value: "other", label: "Other" },
        ],
      },
      {
        name: "priority",
        label: "Priority",
        type: "select",
        required: true,
        options: [
          { value: "low", label: "Low - General question" },
          { value: "medium", label: "Medium - Some impact" },
          { value: "high", label: "High - Significant impact" },
          { value: "urgent", label: "Urgent - Critical issue" },
        ],
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Please describe your issue in detail...",
        rows: 5,
        required: true,
      },
    ],
    submitText: "Submit ticket",
    successMessage: "Your support ticket has been created. We'll respond within 4 hours.",
    contactInfo: {
      email: "support@example.com",
      hours: "24/7 Support available",
    },
  },
  // Sales inquiry form
  {
    headline: "Talk to sales",
    subheadline: "Get a personalized demo and learn how we can help your business grow",
    fields: [
      {
        name: "first_name",
        label: "First name",
        type: "text",
        required: true,
      },
      {
        name: "last_name",
        label: "Last name",
        type: "text",
        required: true,
      },
      {
        name: "email",
        label: "Work email",
        type: "email",
        placeholder: "you@company.com",
        required: true,
      },
      {
        name: "company",
        label: "Company",
        type: "text",
        required: true,
      },
      {
        name: "company_size",
        label: "Company size",
        type: "select",
        required: true,
        options: [
          { value: "1-10", label: "1-10 employees" },
          { value: "11-50", label: "11-50 employees" },
          { value: "51-200", label: "51-200 employees" },
          { value: "201-1000", label: "201-1000 employees" },
          { value: "1000+", label: "1000+ employees" },
        ],
      },
      {
        name: "role",
        label: "Your role",
        type: "select",
        required: true,
        options: [
          { value: "executive", label: "Executive (C-level, VP)" },
          { value: "manager", label: "Manager/Director" },
          { value: "individual", label: "Individual contributor" },
          { value: "other", label: "Other" },
        ],
      },
      {
        name: "budget",
        label: "Budget range",
        type: "select",
        required: false,
        options: [
          { value: "< $10k", label: "Less than $10k" },
          { value: "$10k-$50k", label: "$10k - $50k" },
          { value: "$50k-$100k", label: "$50k - $100k" },
          { value: "> $100k", label: "More than $100k" },
          { value: "not_sure", label: "Not sure yet" },
        ],
      },
      {
        name: "message",
        label: "How can we help?",
        type: "textarea",
        placeholder: "Tell us about your needs and goals...",
        rows: 3,
        required: false,
      },
    ],
    submitText: "Request demo",
    successMessage: "Thanks for your interest! Our sales team will contact you within 24 hours.",
    contactInfo: {
      phone: "+1 (555) 999-8888",
      email: "sales@example.com",
      hours: "Monday - Friday, 9am - 6pm EST",
    },
  },
  // Partnership form
  {
    headline: "Become a partner",
    subheadline: "Join our partner ecosystem and grow your business",
    fields: [
      {
        name: "company_name",
        label: "Company name",
        type: "text",
        required: true,
      },
      {
        name: "contact_name",
        label: "Contact name",
        type: "text",
        required: true,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
      },
      {
        name: "website",
        label: "Website",
        type: "text",
        placeholder: "https://",
        required: false,
      },
      {
        name: "partnership_type",
        label: "Partnership type",
        type: "select",
        required: true,
        options: [
          { value: "technology", label: "Technology partner" },
          { value: "reseller", label: "Reseller/VAR" },
          { value: "consultant", label: "Consultant/SI" },
          { value: "affiliate", label: "Affiliate" },
          { value: "other", label: "Other" },
        ],
      },
      {
        name: "regions",
        label: "Regions you operate in",
        type: "select",
        required: true,
        options: [
          { value: "north_america", label: "North America" },
          { value: "europe", label: "Europe" },
          { value: "asia_pacific", label: "Asia Pacific" },
          { value: "latin_america", label: "Latin America" },
          { value: "middle_east_africa", label: "Middle East & Africa" },
          { value: "global", label: "Global" },
        ],
      },
      {
        name: "description",
        label: "Tell us about your company",
        type: "textarea",
        placeholder: "What you do, your customers, why you want to partner...",
        rows: 4,
        required: true,
      },
    ],
    submitText: "Apply to partner program",
    successMessage: "Thank you for your application. Our partnerships team will review and contact you within 3-5 business days.",
    contactInfo: {
      email: "partners@example.com",
    },
  },
];