import { PricingComparisonProps } from "./index";

export const defaultContent: PricingComparisonProps = {
  headline: "Compare our plans",
  subheadline: "Choose the perfect plan for your needs",
  categories: [
    {
      name: "Core Features",
      features: [
        { name: "Projects", description: "Number of active projects" },
        { name: "Team members", description: "Users per workspace" },
        { name: "Storage", description: "Total storage space" },
        { name: "API requests", description: "Monthly API calls" },
      ],
    },
    {
      name: "Collaboration",
      features: [
        { name: "Guest access" },
        { name: "Team workspaces" },
        { name: "Real-time collaboration" },
        { name: "Comments & mentions" },
      ],
    },
    {
      name: "Security & Compliance",
      features: [
        { name: "Two-factor authentication" },
        { name: "SSO/SAML" },
        { name: "Audit logs" },
        { name: "HIPAA compliance" },
        { name: "SOC 2 certification" },
      ],
    },
    {
      name: "Support",
      features: [
        { name: "Email support" },
        { name: "Priority support" },
        { name: "Phone support" },
        { name: "Dedicated account manager" },
      ],
    },
  ],
  plans: [
    {
      name: "Free",
      price: "$0",
      period: "/month",
      description: "For individuals",
      features: {
        "Projects": "3",
        "Team members": "1",
        "Storage": "5 GB",
        "API requests": "1,000",
        "Guest access": false,
        "Team workspaces": false,
        "Real-time collaboration": false,
        "Comments & mentions": true,
        "Two-factor authentication": true,
        "SSO/SAML": false,
        "Audit logs": false,
        "HIPAA compliance": false,
        "SOC 2 certification": false,
        "Email support": "48hr response",
        "Priority support": false,
        "Phone support": false,
        "Dedicated account manager": false,
      },
      cta: {
        text: "Get Started",
        href: "/signup",
      },
    },
    {
      name: "Pro",
      price: "$29",
      period: "/month",
      description: "For small teams",
      recommended: true,
      features: {
        "Projects": "Unlimited",
        "Team members": "10",
        "Storage": "100 GB",
        "API requests": "100,000",
        "Guest access": true,
        "Team workspaces": true,
        "Real-time collaboration": true,
        "Comments & mentions": true,
        "Two-factor authentication": true,
        "SSO/SAML": false,
        "Audit logs": true,
        "HIPAA compliance": false,
        "SOC 2 certification": true,
        "Email support": "24hr response",
        "Priority support": true,
        "Phone support": false,
        "Dedicated account manager": false,
      },
      cta: {
        text: "Start Free Trial",
        href: "/signup?plan=pro",
      },
    },
    {
      name: "Business",
      price: "$99",
      period: "/month",
      description: "For growing teams",
      features: {
        "Projects": "Unlimited",
        "Team members": "50",
        "Storage": "500 GB",
        "API requests": "500,000",
        "Guest access": true,
        "Team workspaces": true,
        "Real-time collaboration": true,
        "Comments & mentions": true,
        "Two-factor authentication": true,
        "SSO/SAML": true,
        "Audit logs": true,
        "HIPAA compliance": true,
        "SOC 2 certification": true,
        "Email support": "1hr response",
        "Priority support": true,
        "Phone support": true,
        "Dedicated account manager": false,
      },
      cta: {
        text: "Start Free Trial",
        href: "/signup?plan=business",
      },
    },
    {
      name: "Enterprise",
      price: "Custom",
      description: "For large organizations",
      features: {
        "Projects": "Unlimited",
        "Team members": "Unlimited",
        "Storage": "Unlimited",
        "API requests": "Unlimited",
        "Guest access": true,
        "Team workspaces": true,
        "Real-time collaboration": true,
        "Comments & mentions": true,
        "Two-factor authentication": true,
        "SSO/SAML": true,
        "Audit logs": true,
        "HIPAA compliance": true,
        "SOC 2 certification": true,
        "Email support": "Instant",
        "Priority support": true,
        "Phone support": true,
        "Dedicated account manager": true,
      },
      cta: {
        text: "Contact Sales",
        href: "/contact-sales",
      },
    },
  ],
};

export const contentVariations: PricingComparisonProps[] = [
  // Software development tools
  {
    headline: "Find the right plan for your development team",
    categories: [
      {
        name: "Development",
        features: [
          { name: "Private repositories" },
          { name: "CI/CD minutes", description: "Monthly build minutes" },
          { name: "Parallel jobs" },
          { name: "Package storage" },
        ],
      },
      {
        name: "Team Features",
        features: [
          { name: "Code reviews" },
          { name: "Protected branches" },
          { name: "Deploy keys" },
          { name: "Team discussions" },
        ],
      },
      {
        name: "Enterprise",
        features: [
          { name: "LDAP/AD sync" },
          { name: "Advanced security scanning" },
          { name: "Compliance reports" },
          { name: "Custom roles" },
        ],
      },
    ],
    plans: [
      {
        name: "Open Source",
        price: "$0",
        description: "For public projects",
        features: {
          "Private repositories": "0",
          "CI/CD minutes": "2,000",
          "Parallel jobs": "1",
          "Package storage": "500 MB",
          "Code reviews": true,
          "Protected branches": true,
          "Deploy keys": true,
          "Team discussions": true,
          "LDAP/AD sync": false,
          "Advanced security scanning": false,
          "Compliance reports": false,
          "Custom roles": false,
        },
        cta: {
          text: "Get Started",
          href: "/signup",
        },
      },
      {
        name: "Team",
        price: "$15",
        period: "/user/month",
        description: "For private development",
        recommended: true,
        features: {
          "Private repositories": "Unlimited",
          "CI/CD minutes": "10,000",
          "Parallel jobs": "5",
          "Package storage": "50 GB",
          "Code reviews": true,
          "Protected branches": true,
          "Deploy keys": true,
          "Team discussions": true,
          "LDAP/AD sync": false,
          "Advanced security scanning": true,
          "Compliance reports": false,
          "Custom roles": true,
        },
        cta: {
          text: "Start Trial",
          href: "/team-trial",
        },
      },
      {
        name: "Enterprise",
        price: "$35",
        period: "/user/month",
        description: "Advanced security & compliance",
        features: {
          "Private repositories": "Unlimited",
          "CI/CD minutes": "50,000",
          "Parallel jobs": "Unlimited",
          "Package storage": "500 GB",
          "Code reviews": true,
          "Protected branches": true,
          "Deploy keys": true,
          "Team discussions": true,
          "LDAP/AD sync": true,
          "Advanced security scanning": true,
          "Compliance reports": true,
          "Custom roles": true,
        },
        cta: {
          text: "Contact Sales",
          href: "/enterprise",
        },
      },
    ],
  },
  // Marketing platform
  {
    headline: "Marketing tools that grow with you",
    subheadline: "All plans include unlimited contacts",
    categories: [
      {
        name: "Email Marketing",
        features: [
          { name: "Monthly email sends" },
          { name: "Email templates" },
          { name: "A/B testing" },
          { name: "Advanced segmentation" },
        ],
      },
      {
        name: "Automation",
        features: [
          { name: "Marketing workflows" },
          { name: "Lead scoring" },
          { name: "Behavioral triggers" },
          { name: "Multi-channel campaigns" },
        ],
      },
      {
        name: "Analytics",
        features: [
          { name: "Basic reporting" },
          { name: "Custom dashboards" },
          { name: "Revenue attribution" },
          { name: "Predictive analytics" },
        ],
      },
    ],
    plans: [
      {
        name: "Starter",
        price: "$49",
        period: "/month",
        features: {
          "Monthly email sends": "10,000",
          "Email templates": "Basic",
          "A/B testing": false,
          "Advanced segmentation": false,
          "Marketing workflows": "5",
          "Lead scoring": false,
          "Behavioral triggers": false,
          "Multi-channel campaigns": false,
          "Basic reporting": true,
          "Custom dashboards": false,
          "Revenue attribution": false,
          "Predictive analytics": false,
        },
        cta: {
          text: "Start Free",
          href: "/start-free",
        },
      },
      {
        name: "Professional",
        price: "$149",
        period: "/month",
        recommended: true,
        features: {
          "Monthly email sends": "100,000",
          "Email templates": "Premium",
          "A/B testing": true,
          "Advanced segmentation": true,
          "Marketing workflows": "50",
          "Lead scoring": true,
          "Behavioral triggers": true,
          "Multi-channel campaigns": false,
          "Basic reporting": true,
          "Custom dashboards": true,
          "Revenue attribution": true,
          "Predictive analytics": false,
        },
        cta: {
          text: "Start Trial",
          href: "/pro-trial",
        },
      },
      {
        name: "Enterprise",
        price: "$499",
        period: "/month",
        features: {
          "Monthly email sends": "Unlimited",
          "Email templates": "Custom",
          "A/B testing": true,
          "Advanced segmentation": true,
          "Marketing workflows": "Unlimited",
          "Lead scoring": true,
          "Behavioral triggers": true,
          "Multi-channel campaigns": true,
          "Basic reporting": true,
          "Custom dashboards": true,
          "Revenue attribution": true,
          "Predictive analytics": true,
        },
        cta: {
          text: "Get Demo",
          href: "/demo",
        },
      },
    ],
  },
];