export const defaultContent = {
  headline: "Simple, Transparent Pricing",
  subheadline: "Choose the plan that fits your needs. No hidden fees, no surprises.",
  billingOptions: {
    monthly: "Monthly",
    annual: "Annual",
    annualSavings: "Save 20%",
  },
  plans: [
    {
      name: "Starter",
      description: "Perfect for individuals and small projects",
      monthlyPrice: 29,
      annualPrice: 279,
      currency: "$",
      features: [
        "Up to 3 users",
        "5 projects",
        "Basic analytics",
        "24/7 email support",
        "1GB storage",
        "API access",
      ],
      cta: {
        text: "Start Free Trial",
        href: "/signup?plan=starter",
      },
    },
    {
      name: "Professional",
      description: "For growing teams and businesses",
      monthlyPrice: 79,
      annualPrice: 759,
      currency: "$",
      features: [
        "Up to 20 users",
        "Unlimited projects",
        "Advanced analytics",
        "Priority support",
        "100GB storage",
        "Custom integrations",
        "Team collaboration",
        "Advanced security",
      ],
      cta: {
        text: "Start Free Trial",
        href: "/signup?plan=professional",
      },
      featured: true,
      badge: "Most Popular",
    },
    {
      name: "Enterprise",
      description: "For large organizations with custom needs",
      monthlyPrice: 199,
      annualPrice: 1919,
      currency: "$",
      features: [
        "Unlimited users",
        "Unlimited projects",
        "Custom analytics",
        "Dedicated support",
        "Unlimited storage",
        "Custom development",
        "SLA guarantee",
        "On-premise option",
        "Advanced admin controls",
      ],
      cta: {
        text: "Contact Sales",
        href: "/contact?plan=enterprise",
      },
    },
  ],
};