import { TestimonialWallProps } from "./index";

export const defaultContent: TestimonialWallProps = {
  headline: "Wall of love",
  subheadline: "Join thousands of happy customers worldwide",
  testimonials: [
    {
      quote: "Simply amazing! Best investment we've made.",
      author: "Sarah Johnson",
      role: "CEO",
      rating: 5,
      size: "small",
    },
    {
      quote: "This platform has transformed how we work. The features are intuitive, the performance is outstanding, and the support team is always there when we need them.",
      author: "Michael Chen",
      role: "Product Manager",
      company: "TechFlow",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
      rating: 5,
      size: "large",
    },
    {
      quote: "Incredible ROI. Paid for itself in the first month!",
      author: "Emily Davis",
      rating: 5,
      size: "small",
    },
    {
      quote: "The automation features alone have saved us 20 hours per week. Can't imagine working without it.",
      author: "Robert Kim",
      role: "Operations Director",
      company: "ScaleUp Inc",
      rating: 5,
      size: "medium",
    },
    {
      quote: "Game changer for our team!",
      author: "Lisa Martinez",
      rating: 5,
      size: "small",
    },
    {
      quote: "We evaluated 10+ solutions and this was the clear winner. Implementation was smooth and the results were immediate.",
      author: "James Wilson",
      role: "CTO",
      company: "InnovateCo",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop",
      rating: 5,
      size: "large",
    },
    {
      quote: "Outstanding platform with exceptional support.",
      author: "Anna Thompson",
      role: "Designer",
      rating: 5,
      size: "small",
    },
    {
      quote: "The best tool in our tech stack. Period.",
      author: "David Park",
      company: "StartupXYZ",
      rating: 5,
      size: "medium",
    },
    {
      quote: "Exceeded all our expectations. The team loves it!",
      author: "Sophie Chen",
      role: "Team Lead",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
      rating: 5,
      size: "medium",
    },
    {
      quote: "5 stars isn't enough!",
      author: "Tom Anderson",
      rating: 5,
      size: "small",
    },
    {
      quote: "This solution scaled perfectly as we grew from 10 to 100 employees. The flexibility and power are unmatched.",
      author: "Rachel Green",
      role: "VP Growth",
      company: "RapidScale",
      rating: 5,
      size: "large",
    },
    {
      quote: "Wish we had found this sooner!",
      author: "Chris Lee",
      rating: 5,
      size: "small",
    },
  ],
  columns: 3,
  showRatings: true,
};

export const contentVariations: TestimonialWallProps[] = [
  // 4-column layout
  {
    headline: "Loved by developers",
    subheadline: "See why developers choose us",
    testimonials: [
      {
        quote: "Clean API, great docs.",
        author: "Alex Dev",
        rating: 5,
        size: "small",
      },
      {
        quote: "The SDK is beautifully designed. Integration took less than an hour.",
        author: "Maria Garcia",
        role: "Senior Developer",
        rating: 5,
        size: "medium",
      },
      {
        quote: "Best developer experience I've had!",
        author: "John Smith",
        rating: 5,
        size: "small",
      },
      {
        quote: "The documentation is comprehensive and the examples are practical. Everything just works.",
        author: "Li Wei",
        role: "Tech Lead",
        company: "DevCorp",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
        rating: 5,
        size: "large",
      },
      {
        quote: "Fantastic tooling!",
        author: "Emma Wilson",
        rating: 5,
        size: "small",
      },
      {
        quote: "The CLI is intuitive and powerful.",
        author: "Ryan Taylor",
        role: "DevOps Engineer",
        rating: 5,
        size: "medium",
      },
      {
        quote: "Love the TypeScript support!",
        author: "Nina Patel",
        rating: 5,
        size: "small",
      },
      {
        quote: "Webhooks implementation is flawless. Real-time updates work perfectly.",
        author: "Carlos Rodriguez",
        role: "Backend Developer",
        company: "APIFirst",
        rating: 5,
        size: "medium",
      },
    ],
    columns: 4,
    showRatings: true,
  },
  // Without ratings
  {
    headline: "Customer testimonials",
    testimonials: [
      {
        quote: "This product has exceeded our expectations in every way.",
        author: "Jennifer Walsh",
        role: "Marketing Director",
        company: "BrandCo",
        size: "medium",
      },
      {
        quote: "Incredible value!",
        author: "Mark Johnson",
        size: "small",
      },
      {
        quote: "The customer support team goes above and beyond. They truly care about our success.",
        author: "Patricia Brown",
        role: "Customer Success Manager",
        avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
        size: "large",
      },
      {
        quote: "Seamless integration with our existing tools.",
        author: "Steve Miller",
        role: "IT Manager",
        size: "medium",
      },
      {
        quote: "Worth every penny!",
        author: "Diana Prince",
        size: "small",
      },
      {
        quote: "We've tried many solutions, but this is the only one that truly delivers.",
        author: "Kevin Zhang",
        role: "Operations Manager",
        company: "LogisticsCo",
        size: "medium",
      },
    ],
    columns: 3,
    showRatings: false,
  },
  // Mixed sizes for dynamic layout
  {
    headline: "What people are saying",
    testimonials: [
      {
        quote: "Revolutionary platform that has completely changed how we approach our work. The efficiency gains have been remarkable.",
        author: "Amanda Foster",
        role: "Director of Innovation",
        company: "FutureTech",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
        rating: 5,
        size: "large",
      },
      {
        quote: "10/10!",
        author: "Jake Wilson",
        rating: 5,
        size: "small",
      },
      {
        quote: "Perfect solution for our needs.",
        author: "Linda Chen",
        role: "Product Owner",
        rating: 5,
        size: "medium",
      },
      {
        quote: "Absolutely brilliant!",
        author: "Omar Hassan",
        rating: 5,
        size: "small",
      },
      {
        quote: "The analytics dashboard provides insights we never had before. Data-driven decisions are now effortless.",
        author: "Rebecca Stone",
        role: "Data Analyst",
        company: "InsightsCo",
        rating: 5,
        size: "large",
      },
      {
        quote: "Couldn't be happier!",
        author: "Tim Cook",
        rating: 5,
        size: "small",
      },
      {
        quote: "Excellent platform with regular updates and new features.",
        author: "Grace Park",
        role: "Tech Manager",
        rating: 5,
        size: "medium",
      },
      {
        quote: "The best investment we've made in years. ROI was clear from day one.",
        author: "Nathan Brooks",
        role: "CFO",
        company: "FinanceFlow",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop",
        rating: 5,
        size: "large",
      },
      {
        quote: "Simply the best!",
        author: "Zoe Adams",
        rating: 5,
        size: "small",
      },
    ],
    columns: 3,
    showRatings: true,
  },
];